import JSZip from 'jszip'
import { supabase } from './supabaseClient'
import type { ApiResponse } from '../types'
import { triggerHaptic } from '../lib/webapis'

async function getToken(): Promise<string> {
  const {
    data: { session },
  } = await supabase.auth.getSession()
  if (!session) throw new Error('Not authenticated')
  return session.access_token
}

export async function generateWebsite(params: {
  portfolioId: string
  includePortfolioContent: boolean
}): Promise<ApiResponse<{ fullHtml: string; stylePreset: string; websiteId: string }>> {
  const token = await getToken()
  const res = await fetch('/api/website/generate', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${token}`,
    },
    body: JSON.stringify(params),
  })
  const json = (await res.json()) as ApiResponse<{
    fullHtml: string
    stylePreset: string
    websiteId: string
  }>
  if (!res.ok) throw new Error(json.error ?? 'Failed to generate website')
  return json
}

export async function getWebsites(
  portfolioId: string,
): Promise<ApiResponse<{ id: string; style_preset: string; created_at: string }[]>> {
  const token = await getToken()
  const res = await fetch(`/api/website/${portfolioId}`, {
    headers: { Authorization: `Bearer ${token}` },
  })
  const json = (await res.json()) as ApiResponse<
    { id: string; style_preset: string; created_at: string }[]
  >
  if (!res.ok) throw new Error(json.error ?? 'Failed to fetch websites')
  return json
}

export async function getWebsiteHtml(
  websiteId: string,
): Promise<ApiResponse<{ fullHtml: string }>> {
  const token = await getToken()
  const res = await fetch(`/api/website/html/${websiteId}`, {
    headers: { Authorization: `Bearer ${token}` },
  })
  const json = (await res.json()) as ApiResponse<{ fullHtml: string }>
  if (!res.ok) throw new Error(json.error ?? 'Failed to fetch website HTML')
  return json
}

export function downloadWebsiteZip(params: {
  fullHtml: string
  companyName: string
}): void {
  const { fullHtml, companyName } = params
  const zip = new JSZip()

  zip.file('index.html', fullHtml)
  zip.file(
    'README.txt',
    'Generated by Sacred Core Agency.\nOpen index.html in any browser.\nTailwind CSS loaded via CDN.',
  )

  void zip.generateAsync({ type: 'blob' }).then((blob) => {
    const safeName = companyName.replace(/[^a-z0-9]/gi, '-').toLowerCase()
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${safeName}-website.zip`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
    triggerHaptic([50, 30, 50])
  })
}
